name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.presets }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        presets: ['gcc-debug', 'clang-debug', 'release', 'asan-ubsan', 'tsan']
    steps:
      - uses: actions/checkout@v6
      - name: Setup apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14 clang-19 libc++-19-dev libc++abi-19-dev
      - name: Setup CMake & ninja
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # v4.3.3
      - name: Cache googletest
        uses: actions/cache@v5
        with:
          path: build/${{ matrix.presets }}/_deps
          key: gtest-${{ runner.os }}-${{ matrix.presets }}-${{ hashFiles('cmake/gtest.cmake') }}
          restore-keys: gtest-${{ runner.os }}-${{ matrix.presets }}-
      - name: Config-Build-Test
        run: |
          threads=`nproc`
          cmake -S . --preset ${{ matrix.presets }}
          cmake --build --preset ${{ matrix.presets }} --parallel $threads
          ctest --preset ${{ matrix.presets }} --output-on-failure
      - name: Upload failed tests
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: ctest-logs-${{ matrix.presets }}
          path: build/${{ matrix.presets }}/Testing/**/*.log
