name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.presets }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        presets: ['gcc-debug', 'clang-debug', 'release', 'asan-ubsan', 'tsan']
    steps:
      - uses: actions/checkout@v6
      - name: Setup apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libc++-18-dev
      - name: Setup CMake & ninja
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # v4.3.3
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # 1.2.23
        with: ${{ github.job }}
      - name: Config-Build-Test
        run: |
          threads=`nproc`
          cmake -S . --preset ${{ matrix.presets }}
          cmake --build --preset ${{ matrix.presets }} --parallel $threads
          ctest --preset ${{ matrix.presets }} --output-on-failure
      - name: Upload failed tests
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: ctest-logs-${{ matrix.presets }}
          path: build/${{ matrix.presets }}/Testing/**/*.log
