name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.preset }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: gcc-debug
            cc: gcc-14
            cxx: g++-14
          - preset: clang-debug
            cc: clang-19
            cxx: clang++-19
          - preset: release
            cc: clang-19
            cxx: clang++-19
          - preset: asan-ubsan
            cc: clang-19
            cxx: clang++-19
          - preset: tsan
            cc: clang-19
            cxx: clang++-19
    steps:
      - uses: actions/checkout@v6
      - name: Setup apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14 clang-19 libc++-19-dev libc++abi-19-dev lld-19
      - name: Setup CMake & ninja
        uses: lukka/get-cmake@591817e96fcad43505fb4eae36172462abb3a42e # v4.3.3
      - name: Cache googletest
        uses: actions/cache@v5
        with:
          path: build/${{ matrix.preset }}/_deps
          key: gtest-${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('cmake/gtest.cmake') }}
          restore-keys: gtest-${{ runner.os }}-${{ matrix.preset }}-
      - name: Config-Build-Test
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          threads=`nproc`
          cmake -S . --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }} --parallel $threads
          ctest --preset ${{ matrix.preset }} --output-on-failure
      - name: Upload failed tests
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: ctest-logs-${{ matrix.preset }}
          path: build/${{ matrix.preset }}/Testing/**/*.log
